// <auto-generated />
using System;
using HomeIOT.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260601001327_AddModuleVariables")]
    partial class AddModuleVariables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.DeviceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastHeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("production");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.HeartbeatRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClientTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FreeMemoryBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceivedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UptimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceRecordId");

                    b.ToTable("heartbeats", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.LogBatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DroppedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceivedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Truncated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceRecordId");

                    b.ToTable("log_batches", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleAssignmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Entrypoint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("run");

                    b.Property<int>("IntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleDefinitionId");

                    b.HasIndex("ModuleVersionId");

                    b.HasIndex("DeviceRecordId", "ModuleDefinitionId")
                        .IsUnique();

                    b.ToTable("module_assignments", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleDefinitionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultEntrypoint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("run");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId")
                        .IsUnique();

                    b.ToTable("module_definitions", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleResultRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ModuleId");

                    b.ToTable("module_results", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleStatusRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisabledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedStartCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ModuleId");

                    b.ToTable("module_statuses", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleVariableDefRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("string");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleDefinitionId", "Name")
                        .IsUnique();

                    b.ToTable("module_variable_defs", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleVariableValueRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ComputedByServer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastComputedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleAssignmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleAssignmentId", "VariableName")
                        .IsUnique();

                    b.ToTable("module_variable_values", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("PackageSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("module_versions", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.UserRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.HeartbeatRecord", b =>
                {
                    b.HasOne("HomeIOT.Api.Data.Entities.DeviceRecord", "Device")
                        .WithMany("Heartbeats")
                        .HasForeignKey("DeviceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.LogBatchRecord", b =>
                {
                    b.HasOne("HomeIOT.Api.Data.Entities.DeviceRecord", "Device")
                        .WithMany("LogBatches")
                        .HasForeignKey("DeviceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleAssignmentRecord", b =>
                {
                    b.HasOne("HomeIOT.Api.Data.Entities.DeviceRecord", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeIOT.Api.Data.Entities.ModuleDefinitionRecord", "ModuleDefinition")
                        .WithMany("Assignments")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeIOT.Api.Data.Entities.ModuleVersionRecord", "ModuleVersion")
                        .WithMany()
                        .HasForeignKey("ModuleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("ModuleDefinition");

                    b.Navigation("ModuleVersion");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleVariableDefRecord", b =>
                {
                    b.HasOne("HomeIOT.Api.Data.Entities.ModuleDefinitionRecord", "ModuleDefinition")
                        .WithMany("VariableDefs")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleDefinition");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleVariableValueRecord", b =>
                {
                    b.HasOne("HomeIOT.Api.Data.Entities.ModuleAssignmentRecord", "ModuleAssignment")
                        .WithMany("VariableValues")
                        .HasForeignKey("ModuleAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleAssignment");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleVersionRecord", b =>
                {
                    b.HasOne("HomeIOT.Api.Data.Entities.ModuleDefinitionRecord", "ModuleDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleDefinition");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.DeviceRecord", b =>
                {
                    b.Navigation("Heartbeats");

                    b.Navigation("LogBatches");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleAssignmentRecord", b =>
                {
                    b.Navigation("VariableValues");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.ModuleDefinitionRecord", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("VariableDefs");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
