// <auto-generated />
using System;
using HomeIOT.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.DeviceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("production");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.HeartbeatRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClientTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FreeMemoryBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UptimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceRecordId");

                    b.ToTable("heartbeats", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.LogBatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DroppedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceivedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Truncated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceRecordId");

                    b.ToTable("log_batches", (string)null);
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.HeartbeatRecord", b =>
                {
                    b.HasOne("HomeIOT.Api.Data.Entities.DeviceRecord", "Device")
                        .WithMany("Heartbeats")
                        .HasForeignKey("DeviceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.LogBatchRecord", b =>
                {
                    b.HasOne("HomeIOT.Api.Data.Entities.DeviceRecord", "Device")
                        .WithMany("LogBatches")
                        .HasForeignKey("DeviceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HomeIOT.Api.Data.Entities.DeviceRecord", b =>
                {
                    b.Navigation("Heartbeats");

                    b.Navigation("LogBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
